services:
  meson:
    container_name: lo.meson
    ports:
      - "443:443"
    environment:
      TOKENM: 'tlkkumxvfgdenxeb46304c94e7cf0c23'
      PORT: 443
      SIZE: 25
    restart: unless-stopped
    image: lo/meson:202405
  gaga:
    container_name: lo.gaga
    ports:
      - "5060:5060"
      - "36060:36060"
    environment:
      TOKEN: 'lewlqlwjalqflmwd7bb7cb2e6c193e4f'
    restart: unless-stopped
    image: lo/gaga:202405
